"""add ai configs table

Revision ID: 20241228_add_ai_configs
Revises: 20241227_add_saved_audios_table
Create Date: 2024-12-28 18:30:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20241228_add_ai_configs'
down_revision = '20241227_add_saved_audios'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ai_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=100), nullable=True),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('api_key', sa.Text(), nullable=False),
        sa.Column('model', sa.String(length=100), nullable=False),
        sa.Column('base_url', sa.String(length=500), nullable=True),
        sa.Column('temperature', sa.String(length=10), nullable=True, server_default='0.7'),
        sa.Column('max_tokens', sa.Integer(), nullable=True, server_default='4096'),
        sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'),
        sa.Column('is_default', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('last_tested', sa.DateTime(timezone=True), nullable=True),
        sa.Column('test_status', sa.String(length=20), nullable=True),
        sa.Column('test_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['tts_requests.task_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_configs_provider'), 'ai_configs', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_configs_user_id'), 'ai_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_configs_user_id'), table_name='ai_configs')
    op.drop_index(op.f('ix_ai_configs_provider'), table_name='ai_configs')
    op.drop_table('ai_configs')
    # ### end Alembic commands ###
